@id = 9

### //Create Category
POST {{HostAddress}}/categories
Content-Type: application/json
{
  "name":"Cardio"
}

### //Get All Categories
GET {{HostAddress}}/categories
Content-Type: application/json

### //Get Category by ID
GET {{HostAddress}}/categories/{{id}}
Content-Type: application/json

### //Update Category
PUT {{HostAddress}}/categories/{{id}}
Content-Type: application/json
{
  "name":"Weightlifting/crossfit"
}

### //Delete Category
DELETE {{HostAddress}}/categories/{{id}}
Content-Type: application/json

### //Delete all categories
DELETE {{HostAddress}}/categories/delete
Content-Type: application/json